// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMk_Xlf9NH588nwJA_YAZ3e_36sMu_Zec',
    appId: '1:1057744821407:web:6cf8a3523aa40a9f9116aa',
    messagingSenderId: '1057744821407',
    projectId: 'kiit-bus',
    authDomain: 'kiit-bus.firebaseapp.com',
    databaseURL: 'https://kiit-bus-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiit-bus.firebasestorage.app',
    measurementId: 'G-TEVKHLX8FJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfVeWZrGBXFTF_CXnR_v4udCY9YRJsct8',
    appId: '1:1057744821407:ios:4bcdbb578686ad1b9116aa',
    messagingSenderId: '1057744821407',
    projectId: 'kiit-bus',
    databaseURL: 'https://kiit-bus-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiit-bus.firebasestorage.app',
    iosBundleId: 'com.example.kiitBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfVeWZrGBXFTF_CXnR_v4udCY9YRJsct8',
    appId: '1:1057744821407:ios:4bcdbb578686ad1b9116aa',
    messagingSenderId: '1057744821407',
    projectId: 'kiit-bus',
    databaseURL: 'https://kiit-bus-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiit-bus.firebasestorage.app',
    iosBundleId: 'com.example.kiitBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMk_Xlf9NH588nwJA_YAZ3e_36sMu_Zec',
    appId: '1:1057744821407:web:4b7ce2ccd4919b379116aa',
    messagingSenderId: '1057744821407',
    projectId: 'kiit-bus',
    authDomain: 'kiit-bus.firebaseapp.com',
    databaseURL: 'https://kiit-bus-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiit-bus.firebasestorage.app',
    measurementId: 'G-JK14BGK1KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD00z5U-zkG75wma6E8MqB_InDrHW1fSZ4',
    appId: '1:1057744821407:android:9a1ed063c1302e479116aa',
    messagingSenderId: '1057744821407',
    projectId: 'kiit-bus',
    databaseURL: 'https://kiit-bus-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kiit-bus.firebasestorage.app',
  );

}